### ISSUE TITLE
Add a Toeplitz SPMV for a constant-diagonal matrix (e.g. strang matrix)

### ISSUE THREAD

**Issue by willow-ahrens** [willow-ahrens/FinchBenchmarks#53]

**Comment by radha-patel** [comment]
I modified the function that generated banded matrices to generate Toeplitz banded matrices. We have results on Toeplitz matrices with band sizes of 5, 30, and 100. We get a speedup with band sizes 30 and 100. Is there anything else that needs to be done for this issue?

~~~
function banded_matrix(n, b)
    banded = zeros(n, n)
    for i in 1:n
        for j in max(1, i - b):min(n, i + b)
            banded[i, j] = j - i + 1 
        end
    end
    return banded
end
~~~

**Comment by willow-ahrens** [comment]
I think we're all set, we should probably include both versions

**Comment by radha-patel** [comment]
I think the prior version was basically the same thing—I was just setting `banded[i, j]` to `i + j` instead of `j - i + 1`. 

There are some banded matrices in the TACO dataset though. Will see if they perform well with SparseBand!

**Comment by willow-ahrens** [comment]
oh I see what you're saying. I suppose the thought was that we would show toeplitz separate from sparseband, but maybe the taco matrices have it covered.
