### ISSUE TITLE
Julia getting killed when computing SpMV with SparseBand level on Hamm/scircuit matrix

### ISSUE THREAD

**Issue by radha-patel** [willow-ahrens/FinchBenchmarks#54]
Can run SpMV with SparseList and SparseVBL levels on Hamm/scircuit matrix from SuiteSparse. However, Julia REPL keeps getting killed with no error message with SparseBand level, even when @inbounds macro is removed from generated code and Julia is started with `--check-bounds=yes` flag. Not sure what the problem is...
~~~
┌ Info: testing
│   key = "finch_band_unsym"
└   mtx = "Hamm/scircuit"
Killed
~~~

**Comment by willow-ahrens** [comment]
can you run it locally?

**Comment by willow-ahrens** [comment]
does it die if it's the first matrix to run?

**Comment by willow-ahrens** [comment]
okay. we can exempt it for now, but let's take a look at that code at some point later.

**Comment by radha-patel** [comment]
Finding the same issue with `Williams/cop20k_A` (I've just commented it out from the benchmarks - we can look into it later)

**Comment by willow-ahrens** [comment]
can you replicate these locally? If you try to run it outside of a `@belapsed` statement does it work okay? What if you run with --checkbounds=yes?

**Comment by radha-patel** [comment]
Yes, I can replicate this locally and with --check-bounds=yes. It seems the issue is coming from when we are trying to initialize a SparseBand level. For example, the following kills Julia.

~~~
A = SparseMatrixCSC(matrixdepot("Hamm/scircuit"))
A_band = Tensor(Dense(SparseBand(Element(0.0))), A)
~~~

**Comment by radha-patel** [comment]
It dies with nothing :(

~~~
julia> A_band = Tensor(Dense(SparseBand(Element(0.0))), A)
zsh: killed     julia --check-bounds=yes
~~~

**Comment by willow-ahrens** [comment]
we'll have to narrow down what it is, whether it's an allocation or an out of bounds access

**Comment by radha-patel** [comment]
Seems that it could be an OOM error from [this thread](https://discourse.julialang.org/t/best-practice-for-dealing-with-killed-of-julia-exits/95745), but I'll add some print statements to check

**Comment by radha-patel** [comment]
Ah okay, that would make sense. These two matrices also seem to have nonzero values on the far left and far right of most rows—SparseBand is definitely not the right format for them. I don't know if we want to handle this in Finch with a warning or just include a note in the Finch documentation (or maybe just do nothing at all about this).

**Comment by willow-ahrens** [comment]
I think for now, we don't change finch, and we exempt non-banded matrices from sparseBand level
